In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix

In [2]:
data = pd.read_csv('heart.csv')



In [3]:
data.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal  heartdisease  
count  303.000000    303.000000  
mean     2.313531      0.544554  
std      0.612277      0.498835  
min      0.000000      0.000000  
25%      2.000000      0.000000  
50%      2.000000      1.000000  
75%      3.000000      1.000000  
max      3.000000      1.000000

In [4]:
data.isnull().any()


age             False
sex             False
cp              False
trestbps        False
chol            False
fbs             False
restecg         False
thalach         False
exang           False
oldpeak         False
slope           False
ca              False
thal            False
heartdisease    False
dtype: bool

In [5]:
arr=data.to_numpy()


In [6]:

X= arr[:,0:-1]
y= arr[:,-1]
print(X)
print(y)

[[63.  1.  3. ...  0.  0.  1.]
 [37.  1.  2. ...  0.  0.  2.]
 [41.  0.  1. ...  2.  0.  2.]
 ...
 [68.  1.  0. ...  1.  2.  3.]
 [57.  1.  0. ...  1.  1.  3.]
 [57.  0.  1. ...  1.  1.  2.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)

[[ 0.835114    0.73989544  0.0315114  ...  0.955317   -0.69264875
  -0.42921768]
 [ 1.61651954  0.73989544  1.94020175 ... -0.67796691  0.29286491
  -0.42921768]
 [ 0.72348464  0.73989544 -0.92283378 ...  0.955317    0.29286491
   1.13964695]
 ...
 [ 0.16533783  0.73989544  1.94020175 ... -0.67796691 -0.69264875
   1.13964695]
 [-0.83932643  0.73989544  0.98585657 ...  0.955317   -0.69264875
  -0.42921768]
 [ 0.38859655  0.73989544  0.0315114  ... -0.67796691 -0.69264875
  -0.42921768]]
[[ 1.7281489   0.73989544 -0.92283378 ... -2.31125082 -0.69264875
   1.13964695]
 [ 1.05837272  0.73989544  1.94020175 ... -0.67796691 -0.69264875
   1.13964695]
 [ 0.50022591  0.73989544  1.94020175 ... -0.67796691 -0.69264875
   1.13964695]
 ...
 [-0.39280898  0.73989544  0.98585657 ... -0.67796691 -0.69264875
  -0.42921768]
 [ 1.39326081  0.73989544 -0.92283378 ... -0.67796691 -0.69264875
  -0.42921768]
 [ 2.50955443  0.73989544 -0.92283378 ...  0.955317    2.26389222
  -0.42921768]]


In [19]:
ann = tf.keras.models.Sequential()

In [20]:
ann.add(tf.keras.layers.Dense(units=13, activation='relu'))

In [21]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [22]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [24]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [25]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 10)

Epoch 1/10
7/7 [==============================] - 0s 3ms/step - loss: 0.7067 - accuracy: 0.5519
Epoch 2/10
7/7 [==============================] - 0s 1ms/step - loss: 0.6844 - accuracy: 0.5943
Epoch 3/10
7/7 [==============================] - 0s 3ms/step - loss: 0.6665 - accuracy: 0.6274
Epoch 4/10
7/7 [==============================] - 0s 3ms/step - loss: 0.6482 - accuracy: 0.6557
Epoch 5/10
7/7 [==============================] - 0s 1ms/step - loss: 0.6318 - accuracy: 0.6792
Epoch 6/10
7/7 [==============================] - 0s 3ms/step - loss: 0.6165 - accuracy: 0.7028
Epoch 7/10
7/7 [==============================] - 0s 3ms/step - loss: 0.6017 - accuracy: 0.7264
Epoch 8/10
7/7 [==============================] - 0s 1ms/step - loss: 0.5880 - accuracy: 0.7358
Epoch 9/10
7/7 [==============================] - 0s 1ms/step - loss: 0.5740 - accuracy: 0.7547
Epoch 10/10
7/7 [==============================] - 0s 3ms/step - loss: 0.5609 - accuracy: 0.7736


In [26]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0. 0.]
 [1. 1.]
 [1. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 1.]
 [1. 1.]
 [0. 0.]
 [0. 1.]
 [1. 1.]
 [1. 0.]
 [1. 0.]
 [0. 0.]
 [1. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [0. 0.]
 [1. 1.]
 [0. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 0.]
 [1. 0.]
 [0. 0.]
 [1. 1.]
 [0. 1.]
 [0. 1.]
 [1. 1.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 0.]
 [1. 0.]
 [1. 1.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 0.]
 [0. 0.]]


In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix \n",cm)
print("Accuracy",accuracy_score(y_test, y_pred))

Confusion Matrix 
 [[30 14]
 [ 8 39]]
Accuracy 0.7582417582417582
