In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('Logistic.csv')

In [3]:
dataset

Name Gender  Age  Salary  Purchased
0  Divyanshu      M   20   20000          1
1     Mayank      M   23   22000          1
2      Soham      M   25   18000          0
3     Aviral      M   18   25000          1
4    Saksham      M   35   26000          0
5       Riya      F   30   21000          0
6      Shyam      M   27   18000          1
7      Mohan      M   24   17000          1
8      Seeta      F   28   24000          0
9      Geeta      F   32   28000          1

In [4]:
x=dataset.iloc[:,[2,3]].values


In [5]:
y=dataset.iloc[:,4].values


In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
#scaler.fit(x_train)

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
Classifier=LogisticRegression(random_state=0)

In [11]:
Classifier.fit(x_train,y_train)

LogisticRegression(random_state=0)

In [12]:
y_pred=Classifier.predict(x_test)
print(y_pred)

[1 1 0]


In [13]:
from sklearn.metrics import confusion_matrix

In [14]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[1 0]
 [0 2]]


In [15]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [16]:
print("Accuracy ",accuracy_score(y_test,y_pred))

Accuracy  1.0


In [17]:
print("confusion matrix \n",confusion_matrix(y_test,y_pred))

confusion matrix 
 [[1 0]
 [0 2]]
