In [18]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [19]:
irisdata = pd.read_csv("iris_csv.csv")
print(irisdata.head())

   sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa


In [20]:
X = irisdata.drop('class', axis=1)
y = irisdata['class']

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30)

In [22]:
#Using sigmoid kernel
from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, y_train)

SVC(kernel='sigmoid')

In [23]:
y_pred = svclassifier.predict(X_test)

In [24]:
#evaluating the performance

from sklearn.metrics import confusion_matrix,accuracy_score
print("Confusion Matrix\n",confusion_matrix(y_test,y_pred))
print("Accuracy=",accuracy_score(y_test,y_pred)*100)


Confusion Matrix
 [[ 0  0 15]
 [ 0  0 16]
 [ 0  0 14]]
Accuracy= 31.11111111111111


In [25]:
#Using gaussian kernel
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)

SVC()

In [26]:
y_pred = svclassifier.predict(X_test)

In [27]:
#evaluating the performance
from sklearn.metrics import confusion_matrix,accuracy_score
print("Confusion Matrix\n",confusion_matrix(y_test,y_pred))
print("Accuracy=",accuracy_score(y_test,y_pred)*100)


Confusion Matrix
 [[15  0  0]
 [ 0 13  3]
 [ 0  0 14]]
Accuracy= 93.33333333333333
