In [1]:
import tensorflow as tf

In [23]:
tensor_a = tf.constant([[4,6]])
tensor_b = tf.constant([[2, 1]])
tensor_add = tf.add(tensor_a, tensor_b) # addition
tensor_sub=tf.subtract(tensor_a,tensor_b) #subtraction
tensor_mult=tf.multiply(tensor_a,tensor_b) #multiplication
tensor_div=tf.divide(tensor_a,tensor_b) #division
print(tensor_add)
print(tensor_sub)
print(tensor_mult)
print(tensor_div)


tf.Tensor([[6 7]], shape=(1, 2), dtype=int32)
tf.Tensor([[2 5]], shape=(1, 2), dtype=int32)
tf.Tensor([[8 6]], shape=(1, 2), dtype=int32)
tf.Tensor([[2. 6.]], shape=(1, 2), dtype=float64)


In [12]:
# Shape of tensor
m_shape = tf.constant([ [10, 11],
                        [12, 13],
                        [14, 15] ]                      
                     ) 
m_shape.shape

TensorShape([3, 2])