In [1]:
import numpy as np 

In [10]:
lst1 = [10,20,30,40,50] 
lst2 = [1,2,3,4,5]

#creating vectors from list
vctr1 = np.array(lst1) 
print("First vector",vctr1)

vctr2= np.array(lst2)
print("Second Vector",vctr2)

First vector [10 20 30 40 50]
Second Vector [1 2 3 4 5]


In [11]:
#vector addition
vctr_add = vctr1+vctr2
print("Addition=",vctr_add)

Addition= [11 22 33 44 55]


In [12]:
#vector subtraction
vctr_sub = vctr1-vctr2
print("Subtraction=",vctr_sub)

Subtraction= [ 9 18 27 36 45]


In [13]:
#vector multiplication
vctr_mul = vctr1*vctr2
print("Multiplication=",vctr_mul)

Multiplication= [ 10  40  90 160 250]


In [14]:
#vector division
vctr_div = vctr1/vctr2
print("Division=",vctr_div)

Division= [10. 10. 10. 10. 10.]


In [15]:
#dot product
vctr_dot = vctr1.dot(vctr2)
print("Dot product=",vctr_dot)

Dot product= 550


In [20]:
#creating Matrices
x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])
print("first Matrix \n",x)
print("Second Matrix\n",y)

first Matrix 
 [[1 2]
 [4 5]]
Second Matrix
 [[ 7  8]
 [ 9 10]]


In [26]:
# adding matrices
print("Addition=\n",np.add(x,y))
#subtracting matrices
print("Subtraction=\n",np.subtract(x,y))
#multiplying matrices
print("Multiplication=\n",np.multiply(x,y))

 

Addition=
 [[ 8 10]
 [13 15]]
Subtraction=
 [[-6 -6]
 [-5 -5]]
Multiplication=
 [[ 7 16]
 [36 50]]
